### PR TITLE
Add sonarqube

### PR DESCRIPTION
**Pull request by thelitek**
Copypasta from boilerplate

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by falsyvalues** [comment]
Hi there! I don't know how and why but I still have access here.

**Comment by thelitek** [comment]
It's a public repo. No worries thought, I've removed all trade secrets in the previous commit :)

**Comment by johny-gog** [comment]
LOL :D

**Comment by falsyvalues** [comment]
Ha, somehow I had this repo on watch list 👀.

**Comment by andrzejkala** [comment]
Just admit it, you miss us... 🤷‍♂

**Comment by falsyvalues** [comment]
Sure thing, sending ❤️

**Comment by pawel-lewtak** [comment]
How could I miss it?! Sending ❤️ and 💰

**Pull request merged**
